apiVersion: v1
kind: Secret
metadata:
  name: homarr-secrets
  namespace: arr-stack
type: Opaque
stringData:
  SECRET_ENCRYPTION_KEY: "84d6c86e90f6e0e4e23fd81e78652f05e9fd52d57139850bc25dfce3233a6f5f"
