# Homarr Config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-appdata-pvc
  namespace: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 10Gi  # Configuration usually stays small; adjust as needed

