apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controller.yml
  - csi-driver.yml
  - namespace.yml
  - node.yml
  - snapshotter
  - static-pv-synology-media.yaml
  - storage-class.yml
  - synology-nfs-storageclass.yaml
