apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Z8KNn4MCMK3HcJBMkAVANSOlcgVM71U9PVXrgUdPnCCFeS20ksj5ibyaW+W4cSackcaqOVDrd/MRXFVsDmrtJ7VeUAwPpO2yq0nZmHCvHJBsX5T0qviQlpsFEnk9FCgMK7e01m9+F15agToSR9KarmgCx0Qr7tjamxDHVFVnNICc3J3JI/Hb0j8NLbcmcrcXL8f9+So6Pj5ezcxBZaxKVQr0OONWSS7eDeTp4lamnQeNcpeyZbinv7YyFDXQG18jZ8lEfiNxl9wXxJE5orjHXiBbcI6VimfQrt5iseBJkMu5sD6FkKGP0DC90I4=,iv:fcOayrLlWFrCOjHm//sQSb1x+cs/TLZtuBCdElUy21E=,tag:g6d7O3Hyl2ZyWJk03reM0Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170mjhe5pdejvadhan6m8u69e7hulhg9uky585zz3kex958h04ekq2r0gl3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOFJ2dWNIMVhLSHJvMS9j
            NldLK2R2aG5YY3k5b3JhbnRtblU4ZUVFVFVFCjV0aDFnWkhnbjk0UEdqWDNiQ0U4
            eFE5ZXk2SzBlZVQ2YTNOWW40dlV4Zk0KLS0tIDZKQnFNOXZuYkQrTnBQL1NiZWFo
            V3dlYXptd1RudWVNZXh6NFdCaWxURGMK6oI9q0wxiOl7eG07FVaWPEI49ZUU1bB5
            R/hgMMtsp60bdcly995ukLpwlb7wJXaMU3Ebys7HVqbQqB8RS0mrKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T16:29:54Z"
    mac: ENC[AES256_GCM,data:8ifX9FhYqMaSiZjoAyt79FgGhEfnQUDKUoVl0NvECRYp0tmCYoEXeSDgVekSLufguxEZgH8XJ09StVu4vzpiBTRWY3Kgo5LgM+78xzXQUh7eV0ZtHnNOGmRcdxe3c+Vd1B2ajix0wrWfFQfcAZHocbvIHxW4DI3h8c9deIWdauE=,iv:ayOYi0hFr44K04Znm73VhmOPtGjR78RRKHEnoPu8kcY=,tag:+VPkKecSRXfnp3VhJCpe9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
