wallpapers:
  /Users/masondumas/repos/github.com/masondumas/homelab/: squirtle.jpg
  /Users/masondumas/repos/github.com/masondumas/homelab/apps/: wartortle.jpg
  /Users/masondumas/repos/github.com/masondumas/homelab/apps/base/: blastoise.jpg
  default: pikachu.jpg
