apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "0.29.0"

      # version: "58.x"

      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: headlamp
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
#  values:
#    config:
#      # Enable in-cluster configuration
#      useInClusterConfig: true
#    serviceAccount:
#      # Create a service account for Headlamp
#      create: true
#      # Add necessary RBAC rules
#      clusterRoleRules:
#        - apiGroups: ["*"]
#          resources: ["*"]
#          verbs: ["*"]
  # values:
  #   grafana:
  #     adminPassword: mason
  #     ingress:
  #       enabled: true
  #       ingressClassName: traefik

  #       hosts:
  #         - grs.mrmason.org

  #      tls:
  #         - secretName: grafana-general-tls
  #           hosts:
  #             - grs.mrmason.org
