apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "0.28.1"

      # version: "58.x"

      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  # values:
  #   grafana:
  #     adminPassword: mason
  #     ingress:
  #       enabled: true
  #       ingressClassName: traefik

  #       hosts:
  #         - grs.mrmason.org

  #      tls:
  #         - secretName: grafana-general-tls
  #           hosts:
  #             - grs.mrmason.org
