apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: gpu-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: gpu-operator
      version: v25.3.0
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    # Node Feature Discovery is required for the GPU operator
    nfd:
      enabled: true

    # Main operator configuration
    operator:
      defaultRuntime: containerd

    # Driver configuration - let operator manage drivers completely
    driver:
      enabled: true
      repository: nvcr.io/nvidia
      version: "550.90.07" # Use specific stable version
      upgradePolicy:
        autoUpgrade: true
        maxParallelUpgrades: 1
        waitForCompletion:
          timeoutSeconds: 1800
      manager:
        env:
          - name: ENABLE_GPU_POD_EVICTION
            value: "true"
          - name: ENABLE_AUTO_DRAIN
            value: "true"
          - name: DRAIN_USE_FORCE
            value: "true"

    # Toolkit configuration for containerd
    toolkit:
      enabled: true
      env:
      - name: CONTAINERD_CONFIG
        value: /etc/containerd/config.toml
      - name: CONTAINERD_SOCKET
        value: /run/containerd/containerd.sock
      - name: CONTAINERD_RUNTIME_CLASS
        value: nvidia
      - name: CONTAINERD_SET_AS_DEFAULT
        value: "true"

    # Enable Container Device Interface (CDI)
    cdi:
      enabled: true
      default: true

