apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

commonLabels:
  app.kubernetes.io/name: nvidia-gpu-operator
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/managed-by: flux

