apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:n+07a0fc4iOHbmO7R+kR2Aee0EtVZd4toFCQ432kXZUuZpYNbFddafYmSIGkV4jEahHXQ2K7cBHitYFarHlNp0BcqXTS3uoMQbCpuBHZ+K2523K8KFcW5/suLAri1hHG/XO7m2qewx4zE/bO5ejhMSQ/iNuGjjCoShLsJ2XxnwomylMudsIrBnBpwtdAH+m9zxT+7JqzNByTDMNjvbyDMxrgnJzEzYcxsxkyY2hgHInoWdt4OJO01hEKqgrntvL9tX3HdzLwebEl0mghLBnjghLJUJVM404ZoO2b0SxntNKzAgArEiip5QPZmWE=,iv:rXpBkU7Mm9+cIVDsRqttcwW0qW0CbKroV6HwATGctIw=,tag:r4MmCtBikFTFw5UsIyRRqw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials-kavita
sops:
    age:
        - recipient: age170mjhe5pdejvadhan6m8u69e7hulhg9uky585zz3kex958h04ekq2r0gl3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVWlhL2FHbWFwbkxzd1RJ
            UzN4MWcyQUVZODJXOTE2cWtnNWU0b09yREJvCjVGbGJ5VWlzc1VzRHBlTk5GQ21L
            aUQ5Nnp6TXNVYnBhMkRSOWEzWmlFdEEKLS0tIElSWEl5MUZITURwWXk4dHFLZVhx
            dG1qWitCWUxmTHYraDNWeHNOeEprV1UKu2B/SNuvEbnGqfd/5l/tYCzX+RPoMkuw
            PwW+c4YNV25s3ZYxAmSZGVAjoLO4TNS0uETOUppJ7dra65sCNMhGxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-14T17:29:13Z"
    mac: ENC[AES256_GCM,data:VKoeSsTWDFIc0lHXp/6dpYWGaXVm0ZuwCXCCt1KPiTwh69cGdL+2Y8jnA1JUaBAZqhmyC1+VKHYIq3uIKQRFwJHUvZZ/QKwiZOb7dz1bKJQgWiNuptPDXdgwFVpPwuCnMslsuOnBDH6HBkCPZaTwiE8deMqw1g/zuXX0u1KffF8=,iv:xryngbJjDQcsIZ8Dtat1eD3iRm/vXb9xEwiexWrMNoA=,tag:AJvAXbORSQLZ+c0EuEf0pA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
