apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
    #  securityContext:
    #    fsGroup: 33
    #    runAsUser: 33
    #    runAsGroup: 33

      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 5173

          envFrom:
            # - configMapRef:
            #     name: linkding-configmap
            # - secretRef:
            #     name: linkding-container-env

          securityContext:
            allowPrivilegeEscalation: true

          volumeMounts:
            - mountPath: /volume1/OWUI
              name: open-webui-data
      volumes:
        - name: open-webui-data
          persistentVolumeClaim:
            claimName: open-webui-data-pvc
