apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: OWUI-data-pvc
  namespace: OWUI
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 40Gi
