apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiNTg3ZDUxNTMzOWE0MTlkYmViNTk4YTQwMmFiYTBhMTIiLCJUdW5uZWxTZWNyZXQiOiJIdzlBZnJ3RzFTN1JWT3hGRHhtZU9pR1V4eVhyUTY1OEtuUWVObnF3Z0xvPSIsIlR1bm5lbElEIjoiZDQ4YzM5YWYtZDUzNy00YWJjLThmNGYtMmFiNmRiZWQ0M2JiIiwiRW5kcG9pbnQiOiIifQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: tunnel-credentials-jellyseerr
