apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:0c6yDKIev/CvjtWjvg9SmznVT09klaDYB5D8ZfaFJR56BWI6kqg0+82TYF2WwV0xuQueYcNEj/drk51cLn5VqmaF/BhM9MI7MdEOElosIj0jduv6BuYr7pyezkSDlgnW6qcZ3eyUp0qyoMiPR8D9DAv9T2k50RZ8O+9rQTwetbn0nbdnDN6ydnR8D1qznQylCjLiwWzxIJscPh6J2ESYlSC2l2TthAwOguJ0eGz1Nq0KoBhjOOBgpQ5DRC1KnbpbrE2fcT5LMMo0Ia1Odmd90uW4Yw0bCUQ7kP1XN6+4DXMl4rPtLpY93LRG5Jk=,iv:iNUo2bGpb8L+ED84M43rdHK7SNRGc4fyYD5gFhFVX4Q=,tag:f9Apu23M6maC1H+VKD7NfQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170mjhe5pdejvadhan6m8u69e7hulhg9uky585zz3kex958h04ekq2r0gl3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWlNCMU5xYmI2ZXVPVHlD
            dTlZRTlRaXF2QkxEOE51V2xZaXp5dGtUcXdBCktjS1B4YXdEOHoxZ01XUHplZ1Fa
            TTNvUUtjRjk4VjRXK2E0VVdnSGk4VEUKLS0tIHVqQ254SEZ0QzU0TXJUMmVWMWZ2
            azQyU2kyYmdJRU5uV2JqQ2tlZWx3T3cKcuWNSX193cs3TLzqRiMY26mHVT4n4nQC
            QhYAeOKLG6tYJ92vh+Fm8GS1is/NhlbVFxa0mbh4tH/IPB1h5U3C1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-28T14:23:18Z"
    mac: ENC[AES256_GCM,data:CdKrz46XQMBbi/Rx/HpQCZkupcRv14hmxaBP9zcb5vIGnQpJ1HLsFj1QXa6ovqVX/p49bNGcyafyK/WoE3IpDu5RbzA2JOZj2Kan12Z1VzEYuiqomIsjQ4GmrXIm2VBmmSApZB7M8bAWd1xSkNGoj5zO2BERLcg0zkD4etOJHgs=,iv:d2kITsly3wN1Flpmeo+TRoRXkADwkGOq8EjDMrzlmfo=,tag:4dRQ5mxoj7i/v4379+oSXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
