apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-gpu-operator
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-controllers
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/nvidia-gpu-operator/staging/
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age

