apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - ../../base/home-assistant/
  # - cloudflare.yaml
  # - cloudflare-secret.yaml
  # - ingress.yaml
