apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: arr-stack
spec:
  ports:
    - port: 5055
      targetPort: 5055
      protocol: TCP
  selector:
    app: jellyseerr
  type: ClusterIP
