# Jellyseerr PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-data-pvc
  namespace: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 10Gi  # Conifiguration usually stays small; adjust as needed
