apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-data-pvc
  namespace: calibre
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 100Gi
