apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: arr-stack
spec:
  ports:
    - name: http
      port: 8989
      targetPort: 7878
      protocol: TCP
  selector:
    app: radarr
  type: ClusterIP
