apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-refresh
  namespace: home-assistant
spec:
  storageClassName: synology-iscsi-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
